'use server';

import Stripe from 'stripe';
import { headers } from 'next/headers';
import { redirect } from 'next/navigation';

if (!process.env.STRIPE_SECRET_KEY) {
    throw new Error('STRIPE_SECRET_KEY is missing');
}

const stripe = new Stripe(process.env.STRIPE_SECRET_KEY, {
    apiVersion: '2023-10-16',
});

const PRICE_ID_BONUS_PACK = 'price_1SR0X7CcW9oSSZQjX6qJq4qL'; // Placeholder - ideally this comes from config or DB

export async function createCheckoutSession(orderId: string) {
    const origin = headers().get('origin');

    // Create a dynamic price on the fly for simplicity if you don't have products setup yet
    // OR use a fixed price ID if you have created one in Stripe Dashboard.
    // For this implementation, we'll create a session with ad-hoc line items for flexibility.

    const session = await stripe.checkout.sessions.create({
        mode: 'payment',
        line_items: [
            {
                price_data: {
                    currency: 'usd',
                    product_data: {
                        name: 'Bonus Theme Pack',
                        description: 'Unlock all 10+ bonus creative themes generated by our AI.',
                        images: ['https://placehold.co/400x400/png?text=Bonus+Pack'], // Replace with a real asset URL if possible
                    },
                    unit_amount: 900, // $9.00
                },
                quantity: 1,
            },
        ],
        success_url: `${origin}/portal/${orderId}?payment=success`,
        cancel_url: `${origin}/portal/${orderId}?payment=canceled`,
        metadata: {
            orderId: orderId,
            type: 'upsell_unlock',
        },
    });

    if (!session.url) {
        throw new Error('Failed to create checkout session');
    }

    redirect(session.url);
}
